# Generated by Django 4.1.6 on 2023-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studid', models.IntegerField()),
                ('studname', models.CharField(max_length=70)),
                ('studmail', models.EmailField(max_length=70)),
                ('studadd', models.CharField(max_length=40)),
            ],
        ),
    ]
